version: 0.2

phases:

  pre_build:
    commands:

      - echo Logging into ECR

      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER

      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI

  build:
    commands:

      - echo Building Docker image

      - docker build -t frontend-app .

      - docker tag frontend-app:latest $ECR_REPO_URI:$IMAGE_TAG

  post_build:
    commands:

      - echo Pushing Docker image

      - docker push $ECR_REPO_URI:$IMAGE_TAG

      - printf '{"ImageURI":"%s"}' $ECR_REPO_URI:$IMAGE_TAG > imageDetail.json

artifacts:
  files:
    - imageDetail.json
    - deployment.yaml
    - service.yaml
