apiVersion: apps/v1
kind: Deployment

metadata:
  name: static-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: static-app

  template:
    metadata:
      labels:
        app: static-app

    spec:
      containers:
        - name: static-app
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
